### ISSUE TITLE
Prevent items with lore to be signed

### ISSUE THREAD

**Issue by Folas1337** [YingaGaming/Sign#2]
Heyyyy it's me again,

quick feature request once again. Could we get an option to prevent items that already have lore to be signed?
So basically just this in the config.yml:
```yaml
prevent-lore-items: false
```
So it could be set to true and then any items which already have lore could not be signed anymore?

I want to use it in combination with AdvancedEnchantments and it adds its enchantments to the lore but if I add the enchantments and then use '/sign' it'll overwrite the old lore and the item will look as if no enchantment was on the item (even though they still work).

That would be greatly appreciated <3

**Comment by xenorio** [comment]
Hmmm, wouldn't it be better to take the existing lore and just add the signing to that? That way you could still sign those kinda things without losing anything. Modern plugins should not be using lore for actual data storage (especially enchantment stuff, as there is an entire enchant system for that), so i **think** it shouldn't break anything.

**Comment by Folas1337** [comment]
Yeah the enchantments don't stop working but not being able to tell them anymore is annoying. I do agree that appending would be alright but how would you then overwrite old lore of yours and make sure not to kill anything else accidentally?

If you can do that, I'm fine, otherwise might want to consider my approach :)

**Comment by Folas1337** [comment]
Oh yeah for your information, I found another way to make it work for myself through the use of a GUI in game where it's checked if the item you're holding has lore or not and only then it's signed.

So I'll leave the decision up to you if you want to close this issue or keep it as something to think about and maybe add for the future.

I do not need it anymore but I'm happy you're still around and always responsive to issues, that's greatly appreciated and I hope you're having a great day :)

**Comment by xenorio** [comment]
Ah, great! I'll still keep this open as it may be a useful feature for someone out there (if there is anyone. i refuse to implement bStats so idk lol). Just not as any kinda priority ^^

**Comment by xenorio** [comment]
Oh, and i don't know whether or not my day is great yet, literally just opened my eyes ^^

**Comment by Folas1337** [comment]
I no longer need this
